DROP DATABASE IF EXISTS blog_db;
CREATE DATABASE blog_db;
USE blog_db;

CREATE TABLE `user` (
  `userID` INT(30) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `userName` VARCHAR(50) NOT NULL,
  `userPassword` VARCHAR(50) NOT NULL,
)
