DROP DATABASE IF EXISTS users_db;
CREATE DATABASE users_db;
USE users_db;

CREATE TABLE `accounts` (
  `userID` INT(30) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `userName` VARCHAR(50) NOT NULL,
  `userPassword` VARCHAR(50) NOT NULL,
)
